### ISSUE TITLE
一些建议吧

### ISSUE THREAD

**Issue by silencewwt** [pang1567/rsmovie#1]
-    多行注释应该是这个样子的吧……

``` py
def extract_movie_name(str1):
    """
    @:param str1
    """
    pass
```
-    其次我觉得网络请求可以用[requests](http://docs.python-requests.org/en/latest/), 标准库太麻烦啦
-    <del>刚才在睿思上看到这个仓库 现在才发现那帖子已经是坟贴了</del>

**Comment by pang1567** [comment]
多谢  ~
